<?php

declare(strict_types=1);

/**
 * public/index.php — Application Entry Point
 *
 * Apache routes every HTTP request here via .htaccess.
 * This file has exactly four jobs and nothing else:
 *
 *   1. Load the Composer autoloader
 *   2. Load environment variables from .env
 *   3. Define path constants (bootstrap/constants.php)
 *   4. Boot the application (bootstrap/app.php) and run it
 *
 * Nothing else belongs here. All bindings, routes, and configuration
 * live in Service Providers and the bootstrap files.
 */


// 1. autoloader generated by Composer
require_once dirname(__DIR__) . '/vendor/autoload.php';

// 2. load environment variables from .env file
// must be loaded before constants.php
$dotenv = Dotenv\Dotenv::createImmutable(dirname(__DIR__));
$dotenv->load();

// 3. global constants
require_once dirname(__DIR__) . '/bootstrap/constants.php';

// 4. Boot the application
$app = require_once dirname(__DIR__) . '/bootstrap/app.php';

$app->run();